version: "3.6"

networks:
  splunknet:
    driver: bridge
    attachable: true

volumes:
  so1-var:
  so1-etc:

services:
  so1:
    networks:
      splunknet:
        aliases:
          - so1
    image: splunk-debian-9:latest
    container_name: so1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
      - DEBUG=true
    ports:
      - "8000:8000"
      - 8089
      - 8088
    volumes:
      - so1-var:/opt/splunk/var
      - so1-etc:/opt/splunk/etc
